services:
  db:
    image: postgres
    networks:
      - todo-net
    ports:
      - 154432:5432
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck: # 接続確認
      test: ["CMD-SHELL", "psql -U postgres -d todo || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 10s

  api:
    depends_on:
      db:
        conditions: services_healthy
    build:
      context: ./api
      dockerfile: Dockerfile
    port:
      - 8080:8080 # portは一旦8080
    restart: always
    tty: true
    volumes:
      - ./api:/app/api
    working_dir: /app/api
    command: ./gradlew bootRun # ビルドと実行
    networks:
      - todo-net

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./front:/app/front
    working_dir: /app/front
    networks:
      - todo-net

networks:
  todo-net:
volumes: